
SELECT * FROM PortfolioProject.dbo.CovidDeaths
/* THE ABOVE AND BELOW STATEMENTS ARE SAME */
SELECT * FROM PortfolioProject..CovidDeaths

SELECT * FROM PortfolioProject..CovidDeaths ORDER BY 3,4

SELECT * FROM PortfolioProject..CovidVaccinations

SELECT * FROM PortfolioProject..CovidVaccinations ORDER BY 3,4

SELECT DATA THAT WE ARE GOING TO BE USING

SELECT LOCATION, DATE, TOTAL_CASES, NEW_CASES, TOTAL_DEATHS, POPULATION FROM PortfolioProject..CovidDeaths
SELECT LOCATION, DATE, TOTAL_CASES, NEW_CASES, TOTAL_DEATHS, POPULATION FROM PortfolioProject..CovidDeaths ORDER BY 3,4
SELECT LOCATION, DATE, TOTAL_CASES, NEW_CASES, TOTAL_DEATHS, POPULATION FROM PortfolioProject..CovidDeaths ORDER BY 1,2


/* LOOKING AT TOTAL CASES VS TOTAL DEATHS */
/* SHOWS LIKELIHOOD OF DYING IF YOU CONTRACT COVID IN YOUR COUNTRY */
SELECT LOCATION,TOTAL_CASES, TOTAL_DEATHS, (TOTAL_DEATHS/TOTAL_CASES) FROM PortfolioProject..CovidDeaths
SELECT LOCATION,TOTAL_CASES, TOTAL_DEATHS, (TOTAL_DEATHS/TOTAL_CASES)* 100 AS DEATHSPERCENTAGE FROM PortfolioProject..CovidDeaths ORDER BY 1,2
SELECT LOCATION,TOTAL_CASES, TOTAL_DEATHS, (TOTAL_DEATHS/TOTAL_CASES)* 100 AS DEATHSPERCENTAGE FROM PortfolioProject..CovidDeaths WHERE LOCATION LIKE '%STATES%' ORDER BY 1,2

/* LOOKING AT TOTAL CASES VS POPULATION */
/* SHOWS WHAT PERCENTAGE OF POPULATION GOT COVID */
SELECT LOCATION, DATE, POPULATION, TOTAL_CASES, (TOTAL_CASES/POPULATION)*100 AS PERCENTAGE FROM PortfolioProject..CovidDeaths ORDER BY 1,2
SELECT LOCATION, DATE, POPULATION, TOTAL_CASES, (TOTAL_CASES/POPULATION)*100 AS PERCENTAGE FROM PortfolioProject..CovidDeaths WHERE LOCATION LIKE '%STATES%' ORDER BY 1,2

/* LOOKING COUNTRIES WITH HIGHEST INFECTION RATE COMPARED TO POPULATION */

SELECT LOCATION, POPULATION, MAX(TOTAL_CASES) AS HIGHESTINFECTIONCOUNT, MAX(TOTAL_CASES/POPULATION)*100 AS PERCENTPOPULATIONINFECTED FROM PortfolioProject..CovidDeaths GROUP BY LOCATION, POPULATION ORDER BY PERCENTPOPULATIONINFECTED DESC
SELECT LOCATION, POPULATION, MAX(TOTAL_CASES) AS HIGHESTINFECTIONCOUNT, MAX(TOTAL_CASES/POPULATION)*100 AS PERCENTPOPULATIONINFECTED FROM PortfolioProject..CovidDeaths WHERE LOCATION LIKE '%STATES%' GROUP BY LOCATION, POPULATION ORDER BY PERCENTPOPULATIONINFECTED DESC

/* SHOWING COUNTRIES WITH HIGHEST DEATH COUNT PER POPULATION  */

SELECT LOCATION, MAX(TOTAL_DEATHS) AS TOTALDEATHCOUNT FROM PortfolioProject..CovidDeaths GROUP BY LOCATION ORDER BY TOTALDEATHCOUNT DESC
SELECT LOCATION, MAX(TOTAL_DEATHS) AS TOTALDEATHCOUNT FROM PortfolioProject..CovidDeaths WHERE LOCATION LIKE '%STATES%' GROUP BY LOCATION ORDER BY TOTALDEATHCOUNT DESC

/* SHOWING COUNTRIES WITH HIGHEST DEATH COUNT PER POPULATION */
  
SELECT LOCATION, MAX(CAST(TOTAL_DEATHS AS INT)) AS TOTALDEATHCOUNT FROM PortfolioProject..CovidDeaths GROUP BY LOCATION ORDER BY TOTALDEATHCOUNT DESC
SELECT LOCATION, MAX(CAST(TOTAL_DEATHS AS INT)) AS TOTALDEATHCOUNT FROM PortfolioProject..CovidDeaths WHERE LOCATION LIKE '%STATES%' GROUP BY LOCATION ORDER BY TOTALDEATHCOUNT DESC
SELECT LOCATION, MAX(CAST(TOTAL_DEATHS AS INT)) AS TOTALDEATHCOUNT FROM PortfolioProject..CovidDeaths WHERE CONTINENT IS NOT NULL GROUP BY LOCATION ORDER BY TOTALDEATHCOUNT DESC

/*   BREAKING THINGS DOWN BY CONTINENT  */
/* SHOWING CONTINENTS WITH THE HIGHEST DEATH COUNT PER POPULATION */


SELECT CONTINENT, MAX(CAST(TOTAL_DEATHS AS INT)) AS TOTALDEATHCOUNT FROM PortfolioProject..CovidDeaths WHERE CONTINENT IS NOT NULL GROUP BY CONTINENT ORDER BY TOTALDEATHCOUNT DESC
SELECT CONTINENT, MAX(CAST(TOTAL_DEATHS AS INT)) AS TOTALDEATHCOUNT FROM PortfolioProject..CovidDeaths  WHERE LOCATION LIKE '%STATES%' GROUP BY CONTINENT ORDER BY TOTALDEATHCOUNT DESC

/* GLOBAL NUMBERS  */

SELECT SUM(NEW_CASES) AS TOTAL_CASES, SUM(CAST(NEW_DEATHS AS INT)) AS TOTAL_DEATHS, SUM(CAST(NEW_DEATHS AS INT))/SUM(NEW_CASES)*100 AS DEATHPERCENTAGE FROM PortfolioProject..CovidDeaths WHERE continent IS NOT NULL GROUP BY DATE ORDER BY 1,2

SELECT SUM(NEW_CASES) AS TOTAL_CASES, SUM(CAST(NEW_DEATHS AS INT)) AS TOTAL_DEATHS, SUM(CAST(NEW_DEATHS AS INT))/SUM(NEW_CASES)*100 AS DEATHPERCENTAGE FROM PortfolioProject..CovidDeaths WHERE LOCATION LIKE '%STATES%'  GROUP BY DATE ORDER BY 1,2

/* TOTAL POPULATION VS VACCINATIONS  */
/* SHOWS PERCENTAGE OF POPULATION THAT HAS RECEIVED AT LEAST ONE COVID VACCINE  */

SELECT * FROM PortfolioProject..CovidVaccinations
SELECT D.CONTINENT, D.LOCATION, D.DATE,D.POPULATION, V.NEW_VACCINATIONS FROM PortfolioProject..CovidDeaths D JOIN PortfolioProject..CovidVaccinations V ON D.LOCATION=V.LOCATION AND D.DATE=V.DATE WHERE D.CONTINENT IS NOT NULL 
SELECT D.CONTINENT, D.LOCATION, D.DATE,D.POPULATION, V.NEW_VACCINATIONS FROM PortfolioProject..CovidDeaths D JOIN PortfolioProject..CovidVaccinations V ON D.LOCATION=V.LOCATION AND D.DATE=V.DATE WHERE D.CONTINENT IS NOT NULL order by 2,3
SELECT D.CONTINENT, D.LOCATION, D.DATE,D.POPULATION, V.NEW_VACCINATIONS, SUM(CONVERT(INT,V.NEW_VACCINATIONS)) OVER (PARTITION BY D.LOCATION ORDER BY D.LOCATION , D.DATE) AS ROLLINGPEOPLEVACCINATED FROM PortfolioProject..CovidDeaths D JOIN PortfolioProject..CovidVaccinations V ON D.LOCATION=V.LOCATION AND D.DATE=V.DATE WHERE D.CONTINENT IS NOT NULL ORDER BY 2,3
SELECT D.CONTINENT, D.LOCATION, D.DATE,D.POPULATION, V.NEW_VACCINATIONS, SUM(CONVERT(INT,V.NEW_VACCINATIONS)) OVER (PARTITION BY D.LOCATION ORDER BY D.LOCATION , D.DATE) AS ROLLINGPEOPLEVACCINATED, (ROLLINGPEOPLEVACCINATED/POPULATION)*100 FROM PortfolioProject..CovidDeaths D JOIN PortfolioProject..CovidVaccinations V ON D.LOCATION=V.LOCATION AND D.DATE=V.DATE WHERE D.CONTINENT IS NOT NULL ORDER BY 2,3


/* USING CTE TO PERFORM CALCULATION ON PARTITION BY IN PREVIOUS QUERY */


WITH POPVSVAC (CONTINENT,LOCATION,DATE, POPULATION,NEW_VACCINATIONS,ROLLINGPEOPLEVACCINATED)
AS
(
SELECT D.CONTINENT, D.LOCATION, D.DATE,D.POPULATION, V.NEW_VACCINATIONS, SUM(CONVERT(INT,V.NEW_VACCINATIONS)) OVER (PARTITION BY D.LOCATION ORDER BY D.LOCATION , D.DATE) AS ROLLINGPEOPLEVACCINATED FROM PortfolioProject..CovidDeaths D JOIN PortfolioProject..CovidVaccinations V ON D.LOCATION=V.LOCATION AND D.DATE=V.DATE WHERE D.CONTINENT IS NOT NULL 
--ORDER BY 2,3
)
--SELECT * FROM POPVSVAC
SELECT * , (ROLLINGPEOPLEVACCINATED/POPULATION)*100 FROM POPVSVAC


/* USING TEMP TABLE TO PERFORM CALCULATIONS ON PARTITION BY IN PREVIOUS QUERY */


DROP TABLE IF EXISTS #PERCENTPOPULATIONVACCINATED
CREATE TABLE #PERCENTPOPULATIONVACCINATED ( CONTINENT NVARCHAR(255), LOCATION NVARCHAR(255), DATE DATETIME, POPULATION NUMERIC, NEW_VACCINATIONS NUMERIC, ROLLINGPEOPLEVACCINATED NUMERIC)
INSERT INTO #PERCENTPOPULATIONVACCINATED
SELECT D.CONTINENT, D.LOCATION, D.DATE,D.POPULATION, V.NEW_VACCINATIONS, SUM(CONVERT(INT,V.NEW_VACCINATIONS)) OVER (PARTITION BY D.LOCATION ORDER BY D.LOCATION , D.DATE) AS ROLLINGPEOPLEVACCINATED FROM PortfolioProject..CovidDeaths D JOIN PortfolioProject..CovidVaccinations V ON D.LOCATION=V.LOCATION AND D.DATE=V.DATE 
--WHERE D.CONTINENT IS NOT NULL ORDER BY 2,3
SELECT * FROM #PERCENTPOPULATIONVACCINATED
SELECT *, (ROLLINGPEOPLEVACCINATED/POPULATION)*100 FROM #PERCENTPOPULATIONVACCINATED



/* CREATING VIEW STORE DATA FOR LATER VISUALIZATIONS  */



CREATE VIEW PERCENTPOPULATIONVACCINATED AS 
SELECT D.CONTINENT, D.LOCATION, D.DATE,D.POPULATION, V.NEW_VACCINATIONS, SUM(CONVERT(INT,V.NEW_VACCINATIONS)) OVER (PARTITION BY D.LOCATION ORDER BY D.LOCATION , D.DATE) AS ROLLINGPEOPLEVACCINATED FROM PortfolioProject..CovidDeaths D JOIN PortfolioProject..CovidVaccinations V ON D.LOCATION=V.LOCATION AND D.DATE=V.DATE WHERE D.CONTINENT IS NOT NULL 

SELECT * FROM PERCENTPOPULATIONVACCINATED

SELECT TOP (100) [CONTINENT]
      ,[LOCATION]
      ,[DATE]
      ,[POPULATION]
      ,[NEW_VACCINATIONS]
      ,[ROLLINGPEOPLEVACCINATED]
  FROM [PortfolioProject].[dbo].[PERCENTPOPULATIONVACCINATED]


  